imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true


doctrine:
  dbal:
    driver:   pdo_mysql
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "test_symfony"
    user:     "%database_user%"
    password: "%database_password%"
    charset:  UTF8


security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        doctrine:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        main:
            anonymous: ~
            pattern: ^/
            http_basic:
                provider: doctrine